const submissions = [
  {
    id: 1,
    title: 'BCH',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    votes: 15,
    alt: bch,
    submissionImage: '../public/images/bch.jpg',
  },
  {
    id: 1,
    title: 'Bo',
    description: 'Etiam vulputate massa tincidunt justo fringilla condimentum.',
    votes: 15,
    alt: bo,
    submissionImage: '../public/images/submissions/bo.jpg',
  },
  {
    id: 1,
    title: 'Bongu',
    description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed consequat metus non condimentum dignissim.',
    votes: 15,
    alt: bongu,
    submissionImage: '../public/images/submissions/bongu.jpg',
  },
  {
    id: 1,
    title: 'BTV',
    description: 'In blandit risus in tellus venenatis euismod.',
    votes: 15,
    alt: btv,
    submissionImage: '../public/images/submissions/btv.jpg',
  },
  {
    id: 1,
    title: 'Dallas',
    description: 'Nullam nec dapibus leo.',
    votes: 15,
    alt: dallas,
    submissionImage: '../public/images/submissions/dallas.jpg',
  },
  {
    id: 1,
    title: 'DSC',
    description: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    votes: 15,
    alt: dsc,
    submissionImage: '../public/images/submissions/dsc.jpg',
  },
  {
    id: 1,
    title: 'Event',
    description: 'Suspendisse vitae erat ac lectus imperdiet facilisis eu finibus ex.',
    votes: 15,
    alt: dscevent,
    submissionImage: '../public/images/submissions/dscvent.jpg',
  },
  {
    id: 1,
    title: 'Firebase',
    description: 'Nulla sed scelerisque nisi.',
    votes: 15,
    alt: firebase,
    submissionImage: '../public/images/submissions/firebase.jpg',
  },
  {
    id: 1,
    title: 'IT',
    description: 'Duis at neque ut velit posuere cursus.',
    votes: 15,
    alt: it,
    submissionImage: '../public/images/submissions/it.jpg',
  },
  {
    id: 1,
    title: 'Vincom',
    description: 'Vivamus tincidunt elit at nulla gravida, sed lacinia diam egestas.',
    votes: 15,
    alt: vincom,
    submissionImage: '../public/images/submissions/vincom.jpg',
  },
]